<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="LAPTOP-E1NRTU5J" failures="3" tests="8" name="Test" time="2.984" errors="0" timestamp="2024-10-01T21:55:31 CDT">
  <testcase classname="api.test.UserTestsNumpy" name="testPostUser" time="2.138">
    <failure type="io.restassured.path.json.exception.JsonPathException" message="Failed to parse the JSON document">
      <![CDATA[io.restassured.path.json.exception.JsonPathException: Failed to parse the JSON document
at io.restassured.path.json.JsonPath$ExceptionCatcher.invoke(JsonPath.java:1002)
at io.restassured.path.json.JsonPath$4.doParseWith(JsonPath.java:967)
at io.restassured.path.json.JsonPath$JsonParser.parseWith(JsonPath.java:1047)
at io.restassured.path.json.JsonPath.get(JsonPath.java:202)
at io.restassured.path.json.JsonPath.getString(JsonPath.java:352)
at api.test.UserTestsNumpy.testPostUser(UserTestsNumpy.java:54)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
Caused by: groovy.json.JsonException: Lexing failed on line: 1, column: 1, while reading '<', no possible valid JSON value or punctuation could be recognized.
at groovy.json.JsonLexer.nextToken(JsonLexer.java:86)
at groovy.json.JsonLexer$nextToken.call(Unknown Source)
at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:45)
at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:125)
at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:130)
at io.restassured.internal.path.json.ConfigurableJsonSlurper.parse(ConfigurableJsonSlurper.groovy:97)
at io.restassured.internal.path.json.ConfigurableJsonSlurper$parse.callCurrent(Unknown Source)
at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallCurrent(CallSiteArray.java:49)
at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:171)
at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:185)
at io.restassured.internal.path.json.ConfigurableJsonSlurper.parseText(ConfigurableJsonSlurper.groovy:83)
at io.restassured.path.json.JsonPath$4$1.method(JsonPath.java:965)
at io.restassured.path.json.JsonPath$ExceptionCatcher.invoke(JsonPath.java:1000)
... 31 more
... Removed 25 stack frames]]>
    </failure>
  </testcase> <!-- testPostUser -->
  <testcase classname="api.test.UserTestsNumpy" name="testGetAllUsers" time="0.297">
    <failure type="java.lang.AssertionError" message="expected [200] but found [503]">
      <![CDATA[java.lang.AssertionError: expected [200] but found [503]
at api.test.UserTestsNumpy.testGetAllUsers(UserTestsNumpy.java:76)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
... Removed 32 stack frames]]>
    </failure>
  </testcase> <!-- testGetAllUsers -->
  <testcase classname="api.test.UserTestsNumpy" name="GetUserById" time="0.0">
    <skipped/>
  </testcase> <!-- GetUserById -->
  <testcase classname="api.test.UserTestsNumpy" name="GetUserByFirstName" time="0.0">
    <skipped/>
  </testcase> <!-- GetUserByFirstName -->
  <testcase classname="api.test.UserTestsNumpy" name="UpdateUserById" time="0.0">
    <skipped/>
  </testcase> <!-- UpdateUserById -->
  <testcase classname="api.test.UserTestsNumpy" name="DeleteUserByID" time="0.0">
    <skipped/>
  </testcase> <!-- DeleteUserByID -->
  <testcase classname="api.test.UserTestsNumpy" name="testPostUserWithMandatoryDetails" time="0.289">
    <failure type="io.restassured.path.json.exception.JsonPathException" message="Failed to parse the JSON document">
      <![CDATA[io.restassured.path.json.exception.JsonPathException: Failed to parse the JSON document
at io.restassured.path.json.JsonPath$ExceptionCatcher.invoke(JsonPath.java:1002)
at io.restassured.path.json.JsonPath$4.doParseWith(JsonPath.java:967)
at io.restassured.path.json.JsonPath$JsonParser.parseWith(JsonPath.java:1047)
at io.restassured.path.json.JsonPath.get(JsonPath.java:202)
at io.restassured.path.json.JsonPath.getString(JsonPath.java:352)
at api.test.UserTestsNumpy.testPostUserWithMandatoryDetails(UserTestsNumpy.java:185)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
Caused by: groovy.json.JsonException: Lexing failed on line: 1, column: 1, while reading '<', no possible valid JSON value or punctuation could be recognized.
at groovy.json.JsonLexer.nextToken(JsonLexer.java:86)
at groovy.json.JsonLexer$nextToken.call(Unknown Source)
at io.restassured.internal.path.json.ConfigurableJsonSlurper.parse(ConfigurableJsonSlurper.groovy:97)
at io.restassured.internal.path.json.ConfigurableJsonSlurper$parse.callCurrent(Unknown Source)
at io.restassured.internal.path.json.ConfigurableJsonSlurper.parseText(ConfigurableJsonSlurper.groovy:83)
at io.restassured.path.json.JsonPath$4$1.method(JsonPath.java:965)
at io.restassured.path.json.JsonPath$ExceptionCatcher.invoke(JsonPath.java:1000)
... 31 more
... Removed 25 stack frames]]>
    </failure>
  </testcase> <!-- testPostUserWithMandatoryDetails -->
  <testcase classname="api.test.UserTestsNumpy" name="DeleteUserByFirstName" time="0.0">
    <skipped/>
  </testcase> <!-- DeleteUserByFirstName -->
</testsuite> <!-- Test -->
